name: Deploy Task Manager Frontend to AWS 

on:
  push:
    branches:
      - mern-ec2-docker

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Source
              uses: actions/checkout@v4

            - name: Login to Docker Hub Securely
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin || exit 1 

            - name: Build Docker Image
              run: |
                docker buildx build \
                -t harshx19/task-manager-frontend:latest \
                --build-arg VITE_API_BASE_URL="${{ secrets.VITE_API_BASE_URL }}" \
                --push \
                .

            - name: Publish Image to Docker Hub
              run: docker push harshx19/task-manager-frontend:latest

    deploy:
        needs: build
        runs-on: self-hosted
        steps:
            - name: Pull Docker Image from Docker Hub
              run: docker pull harshx19/task-manager-frontend:latest

            - name: Stop and Remove Existing Container
              run: |
                docker stop task-manager-frontend-container || true
                docker rm task-manager-frontend-container || true

            - name: Run Docker Container with Runtime ENV
              run: |
                docker run -d -p 5173:80 \
                --name task-manager-frontend-container \
                -e VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }} \
                harshx19/task-manager-frontend:latest

    verification:
        needs: deploy
        runs-on: self-hosted
        steps:
            - name: Verify Docker Containers
              run: docker ps

            - name: Show Logs
              run: docker logs task-manager-frontend-container
